on:
  repository_dispatch:
    types: [category-update]

jobs:
  update_submodules:
    name: "Update category submodules"
    # Only one job at a time, to avoid confflicts.
    # Shared concurrency with dataset-update jobs.
    concurrency: repo-update
    runs-on: "ubuntu-latest"
    permissions: write-all
    env:
      REPO_NAME: ${{ github.event.client_payload.repo }}
    steps:
      - name: "Checkout the repository"
        uses: actions/checkout@v4
        with:
          ref: main

      - name: "Update submodule"
        run: |
          REPO_PATH="categories/${REPO_NAME#RiverBench/category-}"
          echo "Updating submodule ${REPO_PATH}"
          git submodule update --init --remote "${REPO_PATH}"

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          message: ${{ format('Automatic update of {0}', github.event.client_payload.repo) }}
          default_author: github_actions
          add: categories/*
          pull: '--rebase --autostash'
          push: true

      - name: "Trigger metadata & doc update"
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.PAT_MAIN_REPO_HOOKS }}
          event-type: pre-release
