on:
  issues:
    types: [opened]


jobs:
  autorespond-proposal:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    if: contains(github.event.issue.labels.*.name, 'new dataset') || contains(github.event.issue.labels.*.name, 'new task')

    steps:
      - run: echo ${{ github.event.issue.title }}
