# TODO: trigger by dataset-update

on:
  push:
    branches:
      - main
  # TODO: tagged releases
  workflow_dispatch: {}

jobs:
  pre-release:
    name: "Make a pre-release"
    runs-on: "ubuntu-latest"
    container: ghcr.io/riverbench/ci-worker:main
    permissions: write-all
    steps:
      - name: "Checkout repository (with submodules)"
        uses: actions/checkout@v3
        with:
          path: riverbench
          submodules: true

      - name: "Package profile metadata"
        run: |
          mkdir profiles_out
          mkdir release
          ci-worker package-profiles dev riverbench profiles_out
          tar -czf release/profiles.tar.gz -C profiles_out .

      - name: Fetch the schema repository
        uses: actions/checkout@v3
        with:
          repository: 'RiverBench/schema'
          path: schema

      - name: "Generate documentation"
        run: |
          mkdir docs_out
          ci-worker main-doc-gen dev riverbench profiles_out schema docs_out
          tar -czf release/profiles_docs.tar.gz -C docs_out/profiles .

      - name: Delete previous dev release
        uses: dev-drprasad/delete-tag-and-release@v1.0
        with:
          tag_name: dev
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload files for the release
        uses: ncipollo/release-action@v1.12.0
        with:
          prerelease: true
          draft: false
          makeLatest: false
          tag: "dev"
          name: "Development pre-release"
          artifacts: 'release/*'
          generateReleaseNotes: true

  trigger-doc-update-dev:
    needs: pre-release
    name: "Trigger documentation update (dev)"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Trigger repository_dispatch"
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.PAT_DOC_REPO_HOOKS }}
          repository: RiverBench/riverbench.github.io
          event-type: main-doc-update
          client-payload: '{ "tag": "dev" }'
