# TODO: trigger by dataset-update

on:
  push:
    branches:
      - main
  # TODO: tagged releases
  workflow_dispatch: {}

jobs:
  pre-release:
    name: "Make a pre-release"
    runs-on: "ubuntu-latest"
    container: ghcr.io/riverbench/ci-worker:main
    permissions: write-all
    steps:
      - name: "Checkout repository (with submodules)"
        uses: actions/checkout@v3
        with:
          path: riverbench
          submodules: true

      - name: "Package metadata"
        run: |
          mkdir meta_out
          mkdir release
          ci-worker package-main dev riverbench meta_out
          tar -czf release/profiles.tar.gz -C meta_out/profiles .
          cp meta_out/metadata.ttl release

      - name: Fetch the schema repository
        uses: actions/checkout@v3
        with:
          repository: 'RiverBench/schema'
          path: schema

      - name: "Generate documentation"
        run: |
          mkdir docs_out
          ci-worker main-doc-gen dev riverbench meta_out schema docs_out
          tar -czf release/profiles_docs.tar.gz -C docs_out/profiles .
          rm -r docs_out/profiles
          mkdir readme_out
          mv docs_out/README.md readme_out
          mv riverbench/doc/extra docs_out/documentation
          tar -czf release/docs.tar.gz -C docs_out .

      - name: Upload README.md artifact
        uses: actions/upload-artifact@v3
        with:
          name: readme
          path: readme_out/README.md

      - name: Delete previous dev release
        uses: dev-drprasad/delete-tag-and-release@v1.0
        with:
          tag_name: dev
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload files for the release
        uses: ncipollo/release-action@v1.12.0
        with:
          prerelease: true
          draft: false
          omitDraftDuringUpdate: false
          makeLatest: false
          tag: "dev"
          name: "Development pre-release"
          artifacts: 'release/*'
          generateReleaseNotes: true

  update-readme:
    needs: pre-release
    name: "Update README.md"
    runs-on: "ubuntu-latest"
    permissions: write-all
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v3

      - name: Restore README.md
        uses: actions/download-artifact@v3
        with:
          name: readme

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          message: 'Automatic update of README.md'
          default_author: github_actions
          add: 'README.md'
          push: true

  trigger-doc-update-dev:
    needs: pre-release
    name: "Trigger documentation update (dev)"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Trigger repository_dispatch"
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.PAT_DOC_REPO_HOOKS }}
          repository: RiverBench/riverbench.github.io
          event-type: main-doc-update
          client-payload: '{ "tag": "dev" }'
